apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivia-helm.fullname" . }}-backend
  labels:
    name: {{ include "trivia-helm.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "trivia-helm.fullname" . }}-backend
