apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivia-helm.fullname" . }}-frontend
  labels:
    name: {{ include "trivia-helm.fullname" . }}-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ include "trivia-helm.fullname" . }}-frontend
