apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivia-helm.fullname" . }}-frontend
  labels:
    app: {{ include "trivia-helm.fullname" . }}-frontend
spec:
{{- if eq .Values.environment "test" }}
  replicas: 1
{{- end }}
  selector:
    matchLabels:
      app: {{ include "trivia-helm.fullname" . }}-frontend
  template:
    metadata:
    {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "trivia-helm.fullname" . }}-frontend
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trivia-helm.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
          - name: BACKEND_URL
            value: "http://{{ include "trivia-helm.fullname" . }}-backend"
          - name: BACKEND_PORT
            value: "{{ .Values.backend.service.port }}"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
